//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.25 at 07:11:10 PM PKT 
//


package com.softech.vu360.lms.webservice.message.lmsapi.types.securityroles;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.softech.vu360.lms.webservice.message.lmsapi.types.securityroles package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.softech.vu360.lms.webservice.message.lmsapi.types.securityroles
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UserSecurityRoles }
     * 
     */
    public UserSecurityRoles createUserSecurityRoles() {
        return new UserSecurityRoles();
    }

    /**
     * Create an instance of {@link ResponseUserSecurityRoles }
     * 
     */
    public ResponseUserSecurityRoles createResponseUserSecurityRoles() {
        return new ResponseUserSecurityRoles();
    }

    /**
     * Create an instance of {@link Vu360Users }
     * 
     */
    public Vu360Users createVu360Users() {
        return new Vu360Users();
    }

    /**
     * Create an instance of {@link ValueWithError }
     * 
     */
    public ValueWithError createValueWithError() {
        return new ValueWithError();
    }

    /**
     * Create an instance of {@link UserSecurityRole }
     * 
     */
    public UserSecurityRole createUserSecurityRole() {
        return new UserSecurityRole();
    }

    /**
     * Create an instance of {@link ResponseUserSecurityRole }
     * 
     */
    public ResponseUserSecurityRole createResponseUserSecurityRole() {
        return new ResponseUserSecurityRole();
    }

    /**
     * Create an instance of {@link AssignedSecurityRoleUsers }
     * 
     */
    public AssignedSecurityRoleUsers createAssignedSecurityRoleUsers() {
        return new AssignedSecurityRoleUsers();
    }

    /**
     * Create an instance of {@link UnassignedSecurityRoleUsers }
     * 
     */
    public UnassignedSecurityRoleUsers createUnassignedSecurityRoleUsers() {
        return new UnassignedSecurityRoleUsers();
    }

}
