//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.25 at 07:11:10 PM PKT 
//


package com.softech.vu360.lms.webservice.message.lmsapi.types.securityroles;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.softech.vu360.lms.webservice.message.lmsapi.types.orggroup.OrganizationalGroups;


/**
 * <p>Java class for UserSecurityRole complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserSecurityRole"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SecurityRoleName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Users" type="{http://securityroles.types.lmsapi.message.webservice.lms.vu360.softech.com}Vu360Users"/&gt;
 *         &lt;element name="OrganizationalGroups" type="{http://orggroup.types.lmsapi.message.webservice.lms.vu360.softech.com}OrganizationalGroups" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserSecurityRole", propOrder = {
    "securityRoleName",
    "users",
    "organizationalGroups"
})
public class UserSecurityRole
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "SecurityRoleName", required = true)
    protected String securityRoleName;
    @XmlElement(name = "Users", required = true)
    protected Vu360Users users;
    @XmlElement(name = "OrganizationalGroups")
    protected OrganizationalGroups organizationalGroups;

    /**
     * Gets the value of the securityRoleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecurityRoleName() {
        return securityRoleName;
    }

    /**
     * Sets the value of the securityRoleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecurityRoleName(String value) {
        this.securityRoleName = value;
    }

    /**
     * Gets the value of the users property.
     * 
     * @return
     *     possible object is
     *     {@link Vu360Users }
     *     
     */
    public Vu360Users getUsers() {
        return users;
    }

    /**
     * Sets the value of the users property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vu360Users }
     *     
     */
    public void setUsers(Vu360Users value) {
        this.users = value;
    }

    /**
     * Gets the value of the organizationalGroups property.
     * 
     * @return
     *     possible object is
     *     {@link OrganizationalGroups }
     *     
     */
    public OrganizationalGroups getOrganizationalGroups() {
        return organizationalGroups;
    }

    /**
     * Sets the value of the organizationalGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganizationalGroups }
     *     
     */
    public void setOrganizationalGroups(OrganizationalGroups value) {
        this.organizationalGroups = value;
    }

}
