//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.25 at 07:11:10 PM PKT 
//


package com.softech.vu360.lms.webservice.message.lmsapi.types.customer;

import java.io.Serializable;
import java.math.BigInteger;
import java.time.LocalDate;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import com.softech.vu360.lms.webservice.message.lmsapi.types.address.Address;
import org.w3._2001.xmlschema.Adapter2;


/**
 * <p>Java class for Customer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Customer"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Company" type="{http://customer.types.lmsapi.message.webservice.lms.vu360.softech.com}Company"/&gt;
 *         &lt;element name="Manager" type="{http://customer.types.lmsapi.message.webservice.lms.vu360.softech.com}Manager"/&gt;
 *         &lt;element name="Address" type="{http://address.types.lmsapi.message.webservice.lms.vu360.softech.com}Address" minOccurs="0"/&gt;
 *         &lt;element name="AlternateAddress" type="{http://address.types.lmsapi.message.webservice.lms.vu360.softech.com}Address" minOccurs="0"/&gt;
 *         &lt;element name="UserName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="CustomerType" type="{http://customer.types.lmsapi.message.webservice.lms.vu360.softech.com}CustomerType"/&gt;
 *         &lt;element name="BrandId" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="apiEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *       &lt;attribute name="accountLocked" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *       &lt;attribute name="accountExpired" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *       &lt;attribute name="accountDisabled" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *       &lt;attribute name="visibleOnReport" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *       &lt;attribute name="accountExpirationDate" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *       &lt;attribute name="changePasswordOnNextLogin" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Customer", propOrder = {
    "company",
    "manager",
    "address",
    "alternateAddress",
    "userName",
    "password",
    "customerType",
    "brandId"
})
public class Customer
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Company", required = true)
    protected Company company;
    @XmlElement(name = "Manager", required = true)
    protected Manager manager;
    @XmlElement(name = "Address")
    protected Address address;
    @XmlElement(name = "AlternateAddress")
    protected Address alternateAddress;
    @XmlElement(name = "UserName", required = true)
    protected String userName;
    @XmlElement(name = "Password", required = true)
    protected String password;
    @XmlElement(name = "CustomerType", required = true, defaultValue = "B2B")
    @XmlSchemaType(name = "string")
    protected CustomerType customerType;
    @XmlElement(name = "BrandId", defaultValue = "0")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger brandId;
    @XmlAttribute(name = "apiEnabled")
    protected Boolean apiEnabled;
    @XmlAttribute(name = "accountLocked")
    protected Boolean accountLocked;
    @XmlAttribute(name = "accountExpired")
    protected Boolean accountExpired;
    @XmlAttribute(name = "accountDisabled")
    protected Boolean accountDisabled;
    @XmlAttribute(name = "visibleOnReport")
    protected Boolean visibleOnReport;
    @XmlAttribute(name = "accountExpirationDate")
    @XmlJavaTypeAdapter(Adapter2 .class)
    @XmlSchemaType(name = "date")
    protected LocalDate accountExpirationDate;
    @XmlAttribute(name = "changePasswordOnNextLogin")
    protected Boolean changePasswordOnNextLogin;

    /**
     * Gets the value of the company property.
     * 
     * @return
     *     possible object is
     *     {@link Company }
     *     
     */
    public Company getCompany() {
        return company;
    }

    /**
     * Sets the value of the company property.
     * 
     * @param value
     *     allowed object is
     *     {@link Company }
     *     
     */
    public void setCompany(Company value) {
        this.company = value;
    }

    /**
     * Gets the value of the manager property.
     * 
     * @return
     *     possible object is
     *     {@link Manager }
     *     
     */
    public Manager getManager() {
        return manager;
    }

    /**
     * Sets the value of the manager property.
     * 
     * @param value
     *     allowed object is
     *     {@link Manager }
     *     
     */
    public void setManager(Manager value) {
        this.manager = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setAddress(Address value) {
        this.address = value;
    }

    /**
     * Gets the value of the alternateAddress property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getAlternateAddress() {
        return alternateAddress;
    }

    /**
     * Sets the value of the alternateAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setAlternateAddress(Address value) {
        this.alternateAddress = value;
    }

    /**
     * Gets the value of the userName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the value of the userName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserName(String value) {
        this.userName = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the customerType property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerType }
     *     
     */
    public CustomerType getCustomerType() {
        return customerType;
    }

    /**
     * Sets the value of the customerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerType }
     *     
     */
    public void setCustomerType(CustomerType value) {
        this.customerType = value;
    }

    /**
     * Gets the value of the brandId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBrandId() {
        return brandId;
    }

    /**
     * Sets the value of the brandId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBrandId(BigInteger value) {
        this.brandId = value;
    }

    /**
     * Gets the value of the apiEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isApiEnabled() {
        if (apiEnabled == null) {
            return false;
        } else {
            return apiEnabled;
        }
    }

    /**
     * Sets the value of the apiEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setApiEnabled(Boolean value) {
        this.apiEnabled = value;
    }

    /**
     * Gets the value of the accountLocked property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAccountLocked() {
        if (accountLocked == null) {
            return false;
        } else {
            return accountLocked;
        }
    }

    /**
     * Sets the value of the accountLocked property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAccountLocked(Boolean value) {
        this.accountLocked = value;
    }

    /**
     * Gets the value of the accountExpired property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAccountExpired() {
        if (accountExpired == null) {
            return false;
        } else {
            return accountExpired;
        }
    }

    /**
     * Sets the value of the accountExpired property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAccountExpired(Boolean value) {
        this.accountExpired = value;
    }

    /**
     * Gets the value of the accountDisabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAccountDisabled() {
        if (accountDisabled == null) {
            return false;
        } else {
            return accountDisabled;
        }
    }

    /**
     * Sets the value of the accountDisabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAccountDisabled(Boolean value) {
        this.accountDisabled = value;
    }

    /**
     * Gets the value of the visibleOnReport property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isVisibleOnReport() {
        if (visibleOnReport == null) {
            return true;
        } else {
            return visibleOnReport;
        }
    }

    /**
     * Sets the value of the visibleOnReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setVisibleOnReport(Boolean value) {
        this.visibleOnReport = value;
    }

    /**
     * Gets the value of the accountExpirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public LocalDate getAccountExpirationDate() {
        return accountExpirationDate;
    }

    /**
     * Sets the value of the accountExpirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountExpirationDate(LocalDate value) {
        this.accountExpirationDate = value;
    }

    /**
     * Gets the value of the changePasswordOnNextLogin property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isChangePasswordOnNextLogin() {
        if (changePasswordOnNextLogin == null) {
            return false;
        } else {
            return changePasswordOnNextLogin;
        }
    }

    /**
     * Sets the value of the changePasswordOnNextLogin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setChangePasswordOnNextLogin(Boolean value) {
        this.changePasswordOnNextLogin = value;
    }

}
