//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.25 at 07:11:10 PM PKT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://customer.types.lmsapi.message.webservice.lms.vu360.softech.com", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.softech.vu360.lms.webservice.message.lmsapi.types.customer;
