//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.25 at 07:11:10 PM PKT 
//

package com.softech.vu360.lms.webservice.message.lmsapi.types.user;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for UpdateableUsers complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="UpdateableUsers"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="UpdateableUser" type="{http://user.types.lmsapi.message.webservice.lms.vu360.softech.com}UpdateableUser" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UpdateableUsers", propOrder = { "updateableUser" })
public class UpdateableUsers implements Serializable {

	private final static long serialVersionUID = 1L;
	@XmlElement(name = "UpdateableUser", required = true)
	protected List<UpdateableUser> updateableUser;

	/**
	 * Gets the value of the updateableUser property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the updateableUser property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getUpdateableUser().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link UpdateableUser }
	 * 
	 * 
	 */
	public List<UpdateableUser> getUpdateableUser() {
		if (updateableUser == null) {
			updateableUser = new ArrayList<UpdateableUser>();
		}
		return this.updateableUser;
	}

	public void setUpdateableUser(List<UpdateableUser> updateableUser) {
		this.updateableUser = updateableUser;
	}

}
