//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.25 at 07:11:10 PM PKT 
//


package com.softech.vu360.lms.webservice.message.lmsapi.types.trainingplan;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.softech.vu360.lms.webservice.message.lmsapi.types.trainingplan package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.softech.vu360.lms.webservice.message.lmsapi.types.trainingplan
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TrainingPlans }
     * 
     */
    public TrainingPlans createTrainingPlans() {
        return new TrainingPlans();
    }

    /**
     * Create an instance of {@link ResponseTrainingPlans }
     * 
     */
    public ResponseTrainingPlans createResponseTrainingPlans() {
        return new ResponseTrainingPlans();
    }

    /**
     * Create an instance of {@link TrainingPlanLearner }
     * 
     */
    public TrainingPlanLearner createTrainingPlanLearner() {
        return new TrainingPlanLearner();
    }

    /**
     * Create an instance of {@link TrainingPlanToLearner }
     * 
     */
    public TrainingPlanToLearner createTrainingPlanToLearner() {
        return new TrainingPlanToLearner();
    }

    /**
     * Create an instance of {@link TrainingPlanAssignResponsed }
     * 
     */
    public TrainingPlanAssignResponsed createTrainingPlanAssignResponsed() {
        return new TrainingPlanAssignResponsed();
    }

    /**
     * Create an instance of {@link Courses }
     * 
     */
    public Courses createCourses() {
        return new Courses();
    }

    /**
     * Create an instance of {@link Course }
     * 
     */
    public Course createCourse() {
        return new Course();
    }

    /**
     * Create an instance of {@link TrainingPlan }
     * 
     */
    public TrainingPlan createTrainingPlan() {
        return new TrainingPlan();
    }

    /**
     * Create an instance of {@link ResponseTrainingPlan }
     * 
     */
    public ResponseTrainingPlan createResponseTrainingPlan() {
        return new ResponseTrainingPlan();
    }

    /**
     * Create an instance of {@link TrainingPlanResponseCourses }
     * 
     */
    public TrainingPlanResponseCourses createTrainingPlanResponseCourses() {
        return new TrainingPlanResponseCourses();
    }

    /**
     * Create an instance of {@link TrainingPlanResponseCourse }
     * 
     */
    public TrainingPlanResponseCourse createTrainingPlanResponseCourse() {
        return new TrainingPlanResponseCourse();
    }

    /**
     * Create an instance of {@link TrainingPlanAssignResp }
     * 
     */
    public TrainingPlanAssignResp createTrainingPlanAssignResp() {
        return new TrainingPlanAssignResp();
    }

}
