//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.25 at 07:11:10 PM PKT 
//


package com.softech.vu360.lms.webservice.message.lmsapi.types.orggroup;

import java.io.Serializable;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AddOrgGroupByParentIdOrganizationalGroup complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AddOrgGroupByParentIdOrganizationalGroup"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ParentId" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="OrgGroupName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddOrgGroupByParentIdOrganizationalGroup", propOrder = {
    "parentId",
    "orgGroupName"
})
public class AddOrgGroupByParentIdOrganizationalGroup
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "ParentId", required = true)
    protected BigInteger parentId;
    @XmlElement(name = "OrgGroupName", required = true)
    protected String orgGroupName;

    /**
     * Gets the value of the parentId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getParentId() {
        return parentId;
    }

    /**
     * Sets the value of the parentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setParentId(BigInteger value) {
        this.parentId = value;
    }

    /**
     * Gets the value of the orgGroupName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgGroupName() {
        return orgGroupName;
    }

    /**
     * Sets the value of the orgGroupName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgGroupName(String value) {
        this.orgGroupName = value;
    }

}
