//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.25 at 07:11:10 PM PKT 
//


package com.softech.vu360.lms.webservice.message.lmsapi.types.orggroup;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.softech.vu360.lms.webservice.message.lmsapi.types.orggroup package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RegisterOrganizationalGroups_QNAME = new QName("http://orggroup.types.lmsapi.message.webservice.lms.vu360.softech.com", "RegisterOrganizationalGroups");
    private final static QName _RegisterOrganizationalGroup_QNAME = new QName("http://orggroup.types.lmsapi.message.webservice.lms.vu360.softech.com", "RegisterOrganizationalGroup");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.softech.vu360.lms.webservice.message.lmsapi.types.orggroup
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RegisterOrganizationalGroups }
     * 
     */
    public RegisterOrganizationalGroups createRegisterOrganizationalGroups() {
        return new RegisterOrganizationalGroups();
    }

    /**
     * Create an instance of {@link RegisterOrganizationalGroup }
     * 
     */
    public RegisterOrganizationalGroup createRegisterOrganizationalGroup() {
        return new RegisterOrganizationalGroup();
    }

    /**
     * Create an instance of {@link ValueWithError }
     * 
     */
    public ValueWithError createValueWithError() {
        return new ValueWithError();
    }

    /**
     * Create an instance of {@link InvalidOrgGroupValueWithError }
     * 
     */
    public InvalidOrgGroupValueWithError createInvalidOrgGroupValueWithError() {
        return new InvalidOrgGroupValueWithError();
    }

    /**
     * Create an instance of {@link OrganizationalGroups }
     * 
     */
    public OrganizationalGroups createOrganizationalGroups() {
        return new OrganizationalGroups();
    }

    /**
     * Create an instance of {@link AssignedOrganizationalGroups }
     * 
     */
    public AssignedOrganizationalGroups createAssignedOrganizationalGroups() {
        return new AssignedOrganizationalGroups();
    }

    /**
     * Create an instance of {@link UnassignedOrganizationalGroups }
     * 
     */
    public UnassignedOrganizationalGroups createUnassignedOrganizationalGroups() {
        return new UnassignedOrganizationalGroups();
    }

    /**
     * Create an instance of {@link OrgGroup }
     * 
     */
    public OrgGroup createOrgGroup() {
        return new OrgGroup();
    }

    /**
     * Create an instance of {@link NewOrganizationalGroups }
     * 
     */
    public NewOrganizationalGroups createNewOrganizationalGroups() {
        return new NewOrganizationalGroups();
    }

    /**
     * Create an instance of {@link ResponseOrganizationalGroup }
     * 
     */
    public ResponseOrganizationalGroup createResponseOrganizationalGroup() {
        return new ResponseOrganizationalGroup();
    }

    /**
     * Create an instance of {@link DeletedOrganizationalGroup }
     * 
     */
    public DeletedOrganizationalGroup createDeletedOrganizationalGroup() {
        return new DeletedOrganizationalGroup();
    }

    /**
     * Create an instance of {@link AddOrgGroupByParentIdOrganizationalGroups }
     * 
     */
    public AddOrgGroupByParentIdOrganizationalGroups createAddOrgGroupByParentIdOrganizationalGroups() {
        return new AddOrgGroupByParentIdOrganizationalGroups();
    }

    /**
     * Create an instance of {@link AddOrgGroupByParentIdOrganizationalGroup }
     * 
     */
    public AddOrgGroupByParentIdOrganizationalGroup createAddOrgGroupByParentIdOrganizationalGroup() {
        return new AddOrgGroupByParentIdOrganizationalGroup();
    }

    /**
     * Create an instance of {@link UpdateOrganizationalGroup }
     * 
     */
    public UpdateOrganizationalGroup createUpdateOrganizationalGroup() {
        return new UpdateOrganizationalGroup();
    }

    /**
     * Create an instance of {@link DeleteOrganizationGroups }
     * 
     */
    public DeleteOrganizationGroups createDeleteOrganizationGroups() {
        return new DeleteOrganizationGroups();
    }

    /**
     * Create an instance of {@link InvalidOrganizationalGroups }
     * 
     */
    public InvalidOrganizationalGroups createInvalidOrganizationalGroups() {
        return new InvalidOrganizationalGroups();
    }

    /**
     * Create an instance of {@link GetOrgGroupById }
     * 
     */
    public GetOrgGroupById createGetOrgGroupById() {
        return new GetOrgGroupById();
    }

    /**
     * Create an instance of {@link GetOrgGroupIdByName }
     * 
     */
    public GetOrgGroupIdByName createGetOrgGroupIdByName() {
        return new GetOrgGroupIdByName();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegisterOrganizationalGroups }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://orggroup.types.lmsapi.message.webservice.lms.vu360.softech.com", name = "RegisterOrganizationalGroups")
    public JAXBElement<RegisterOrganizationalGroups> createRegisterOrganizationalGroups(RegisterOrganizationalGroups value) {
        return new JAXBElement<RegisterOrganizationalGroups>(_RegisterOrganizationalGroups_QNAME, RegisterOrganizationalGroups.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegisterOrganizationalGroup }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://orggroup.types.lmsapi.message.webservice.lms.vu360.softech.com", name = "RegisterOrganizationalGroup")
    public JAXBElement<RegisterOrganizationalGroup> createRegisterOrganizationalGroup(RegisterOrganizationalGroup value) {
        return new JAXBElement<RegisterOrganizationalGroup>(_RegisterOrganizationalGroup_QNAME, RegisterOrganizationalGroup.class, null, value);
    }

}
