//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.25 at 07:11:10 PM PKT 
//

package com.softech.vu360.lms.webservice.message.lmsapi.types.orggroup;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for RegisterOrganizationalGroups complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="RegisterOrganizationalGroups"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RegisterOrganizationalGroup" type="{http://orggroup.types.lmsapi.message.webservice.lms.vu360.softech.com}RegisterOrganizationalGroup" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegisterOrganizationalGroups", propOrder = { "registerOrganizationalGroup" })
public class RegisterOrganizationalGroups implements Serializable {

	private final static long serialVersionUID = 1L;
	@XmlElement(name = "RegisterOrganizationalGroup", required = true)
	protected List<RegisterOrganizationalGroup> registerOrganizationalGroup;

	/**
	 * Gets the value of the registerOrganizationalGroup property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the registerOrganizationalGroup property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getRegisterOrganizationalGroup().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link RegisterOrganizationalGroup }
	 * 
	 * 
	 */
	public List<RegisterOrganizationalGroup> getRegisterOrganizationalGroup() {
		if (registerOrganizationalGroup == null) {
			registerOrganizationalGroup = new ArrayList<RegisterOrganizationalGroup>();
		}
		return this.registerOrganizationalGroup;
	}

	public void setRegisterOrganizationalGroup(List<RegisterOrganizationalGroup> registerOrganizationalGroup) {
		this.registerOrganizationalGroup = registerOrganizationalGroup;
	}

}
