//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.25 at 07:11:10 PM PKT 
//


package com.softech.vu360.lms.webservice.message.lmsapi.types.enrollment;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.softech.vu360.lms.webservice.message.lmsapi.types.enrollment package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.softech.vu360.lms.webservice.message.lmsapi.types.enrollment
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LearnerCourses }
     * 
     */
    public LearnerCourses createLearnerCourses() {
        return new LearnerCourses();
    }

    /**
     * Create an instance of {@link LearnerEnrolledCourses }
     * 
     */
    public LearnerEnrolledCourses createLearnerEnrolledCourses() {
        return new LearnerEnrolledCourses();
    }

    /**
     * Create an instance of {@link Learners }
     * 
     */
    public Learners createLearners() {
        return new Learners();
    }

    /**
     * Create an instance of {@link LearnerEnrollCourses }
     * 
     */
    public LearnerEnrollCourses createLearnerEnrollCourses() {
        return new LearnerEnrollCourses();
    }

    /**
     * Create an instance of {@link FailedCourses }
     * 
     */
    public FailedCourses createFailedCourses() {
        return new FailedCourses();
    }

    /**
     * Create an instance of {@link EnrolledCourses }
     * 
     */
    public EnrolledCourses createEnrolledCourses() {
        return new EnrolledCourses();
    }

    /**
     * Create an instance of {@link EnrolledCourse }
     * 
     */
    public EnrolledCourse createEnrolledCourse() {
        return new EnrolledCourse();
    }

}
