//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.25 at 07:11:10 PM PKT 
//


package com.softech.vu360.lms.webservice.message.lmsapi.serviceoperations.orggroup;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.softech.vu360.lms.webservice.message.lmsapi.types.orggroup.OrgGroup;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ParentOrgGroupHierarchy" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="OrgGroup" type="{http://orggroup.types.lmsapi.message.webservice.lms.vu360.softech.com}OrgGroup"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="customerCode" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="key" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "parentOrgGroupHierarchy",
    "orgGroup"
})
@XmlRootElement(name = "AddOrgGroupByHierarchyRequest")
public class AddOrgGroupByHierarchyRequest
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "ParentOrgGroupHierarchy", required = true)
    protected String parentOrgGroupHierarchy;
    @XmlElement(name = "OrgGroup", required = true)
    protected OrgGroup orgGroup;
    @XmlAttribute(name = "customerCode", required = true)
    protected String customerCode;
    @XmlAttribute(name = "key", required = true)
    protected String key;

    /**
     * Gets the value of the parentOrgGroupHierarchy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentOrgGroupHierarchy() {
        return parentOrgGroupHierarchy;
    }

    /**
     * Sets the value of the parentOrgGroupHierarchy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentOrgGroupHierarchy(String value) {
        this.parentOrgGroupHierarchy = value;
    }

    /**
     * Gets the value of the orgGroup property.
     * 
     * @return
     *     possible object is
     *     {@link OrgGroup }
     *     
     */
    public OrgGroup getOrgGroup() {
        return orgGroup;
    }

    /**
     * Sets the value of the orgGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrgGroup }
     *     
     */
    public void setOrgGroup(OrgGroup value) {
        this.orgGroup = value;
    }

    /**
     * Gets the value of the customerCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerCode() {
        return customerCode;
    }

    /**
     * Sets the value of the customerCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerCode(String value) {
        this.customerCode = value;
    }

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKey(String value) {
        this.key = value;
    }

}
