//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.25 at 07:11:10 PM PKT 
//


package com.softech.vu360.lms.webservice.message.lmsapi.serviceoperations.orggroup;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.softech.vu360.lms.webservice.message.lmsapi.serviceoperations.orggroup package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.softech.vu360.lms.webservice.message.lmsapi.serviceoperations.orggroup
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddOrgGroupByHierarchyRequest }
     * 
     */
    public AddOrgGroupByHierarchyRequest createAddOrgGroupByHierarchyRequest() {
        return new AddOrgGroupByHierarchyRequest();
    }

    /**
     * Create an instance of {@link AddOrgGroupByHierarchyResponse }
     * 
     */
    public AddOrgGroupByHierarchyResponse createAddOrgGroupByHierarchyResponse() {
        return new AddOrgGroupByHierarchyResponse();
    }

    /**
     * Create an instance of {@link AddOrgGroupByParentIdRequest }
     * 
     */
    public AddOrgGroupByParentIdRequest createAddOrgGroupByParentIdRequest() {
        return new AddOrgGroupByParentIdRequest();
    }

    /**
     * Create an instance of {@link AddOrgGroupByParentIdResponse }
     * 
     */
    public AddOrgGroupByParentIdResponse createAddOrgGroupByParentIdResponse() {
        return new AddOrgGroupByParentIdResponse();
    }

    /**
     * Create an instance of {@link UpdateOrganizationGroupRequest }
     * 
     */
    public UpdateOrganizationGroupRequest createUpdateOrganizationGroupRequest() {
        return new UpdateOrganizationGroupRequest();
    }

    /**
     * Create an instance of {@link UpdateOrganizationGroupResponse }
     * 
     */
    public UpdateOrganizationGroupResponse createUpdateOrganizationGroupResponse() {
        return new UpdateOrganizationGroupResponse();
    }

    /**
     * Create an instance of {@link DeleteOrganizationGroupRequest }
     * 
     */
    public DeleteOrganizationGroupRequest createDeleteOrganizationGroupRequest() {
        return new DeleteOrganizationGroupRequest();
    }

    /**
     * Create an instance of {@link DeleteOrganizationGroupResponse }
     * 
     */
    public DeleteOrganizationGroupResponse createDeleteOrganizationGroupResponse() {
        return new DeleteOrganizationGroupResponse();
    }

    /**
     * Create an instance of {@link GetOrgGroupByIdRequest }
     * 
     */
    public GetOrgGroupByIdRequest createGetOrgGroupByIdRequest() {
        return new GetOrgGroupByIdRequest();
    }

    /**
     * Create an instance of {@link GetOrgGroupByIdResponse }
     * 
     */
    public GetOrgGroupByIdResponse createGetOrgGroupByIdResponse() {
        return new GetOrgGroupByIdResponse();
    }

    /**
     * Create an instance of {@link GetOrgGroupIdByNameRequest }
     * 
     */
    public GetOrgGroupIdByNameRequest createGetOrgGroupIdByNameRequest() {
        return new GetOrgGroupIdByNameRequest();
    }

    /**
     * Create an instance of {@link GetOrgGroupIdByNameResponse }
     * 
     */
    public GetOrgGroupIdByNameResponse createGetOrgGroupIdByNameResponse() {
        return new GetOrgGroupIdByNameResponse();
    }

}
