//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.25 at 07:11:10 PM PKT 
//


package com.softech.vu360.lms.webservice.message.lmsapi.serviceoperations.enrollment;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.softech.vu360.lms.webservice.message.lmsapi.types.enrollment.LearnerEnrollCourses;
import com.softech.vu360.lms.webservice.message.lmsapi.types.enrollment.Learners;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Learners" type="{http://enrollment.types.lmsapi.message.webservice.lms.vu360.softech.com}Learners"/&gt;
 *         &lt;element name="Courses" type="{http://enrollment.types.lmsapi.message.webservice.lms.vu360.softech.com}LearnerEnrollCourses"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="customerCode" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="key" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="notifyLearnersByEmail" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "learners",
    "courses"
})
@XmlRootElement(name = "BulkEnrollmentRequest")
public class BulkEnrollmentRequest
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Learners", required = true)
    protected Learners learners;
    @XmlElement(name = "Courses", required = true)
    protected LearnerEnrollCourses courses;
    @XmlAttribute(name = "customerCode", required = true)
    protected String customerCode;
    @XmlAttribute(name = "key", required = true)
    protected String key;
    @XmlAttribute(name = "notifyLearnersByEmail")
    protected Boolean notifyLearnersByEmail;

    /**
     * Gets the value of the learners property.
     * 
     * @return
     *     possible object is
     *     {@link Learners }
     *     
     */
    public Learners getLearners() {
        return learners;
    }

    /**
     * Sets the value of the learners property.
     * 
     * @param value
     *     allowed object is
     *     {@link Learners }
     *     
     */
    public void setLearners(Learners value) {
        this.learners = value;
    }

    /**
     * Gets the value of the courses property.
     * 
     * @return
     *     possible object is
     *     {@link LearnerEnrollCourses }
     *     
     */
    public LearnerEnrollCourses getCourses() {
        return courses;
    }

    /**
     * Sets the value of the courses property.
     * 
     * @param value
     *     allowed object is
     *     {@link LearnerEnrollCourses }
     *     
     */
    public void setCourses(LearnerEnrollCourses value) {
        this.courses = value;
    }

    /**
     * Gets the value of the customerCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerCode() {
        return customerCode;
    }

    /**
     * Sets the value of the customerCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerCode(String value) {
        this.customerCode = value;
    }

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKey(String value) {
        this.key = value;
    }

    /**
     * Gets the value of the notifyLearnersByEmail property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isNotifyLearnersByEmail() {
        if (notifyLearnersByEmail == null) {
            return false;
        } else {
            return notifyLearnersByEmail;
        }
    }

    /**
     * Sets the value of the notifyLearnersByEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNotifyLearnersByEmail(Boolean value) {
        this.notifyLearnersByEmail = value;
    }

}
