//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.25 at 07:11:10 PM PKT 
//


package com.softech.vu360.lms.webservice.message.lmsapi.serviceoperations.trainingplan;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.softech.vu360.lms.webservice.message.lmsapi.serviceoperations.trainingplan package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.softech.vu360.lms.webservice.message.lmsapi.serviceoperations.trainingplan
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateTrainingPlanRequest }
     * 
     */
    public CreateTrainingPlanRequest createCreateTrainingPlanRequest() {
        return new CreateTrainingPlanRequest();
    }

    /**
     * Create an instance of {@link CreateTrainingPlanResponse }
     * 
     */
    public CreateTrainingPlanResponse createCreateTrainingPlanResponse() {
        return new CreateTrainingPlanResponse();
    }

    /**
     * Create an instance of {@link AssignTrainingPlanToLearnerRequest }
     * 
     */
    public AssignTrainingPlanToLearnerRequest createAssignTrainingPlanToLearnerRequest() {
        return new AssignTrainingPlanToLearnerRequest();
    }

    /**
     * Create an instance of {@link AssignTrainingPlanToLearnerResponse }
     * 
     */
    public AssignTrainingPlanToLearnerResponse createAssignTrainingPlanToLearnerResponse() {
        return new AssignTrainingPlanToLearnerResponse();
    }

    /**
     * Create an instance of {@link AssignTrainingPlanToUserGroupRequest }
     * 
     */
    public AssignTrainingPlanToUserGroupRequest createAssignTrainingPlanToUserGroupRequest() {
        return new AssignTrainingPlanToUserGroupRequest();
    }

    /**
     * Create an instance of {@link AssignTrainingPlanToUserGroupResponse }
     * 
     */
    public AssignTrainingPlanToUserGroupResponse createAssignTrainingPlanToUserGroupResponse() {
        return new AssignTrainingPlanToUserGroupResponse();
    }

}
