//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.25 at 07:11:10 PM PKT 
//


package com.softech.vu360.lms.webservice.message.lmsapi.serviceoperations.usergroup;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.softech.vu360.lms.webservice.message.lmsapi.serviceoperations.usergroup package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.softech.vu360.lms.webservice.message.lmsapi.serviceoperations.usergroup
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddUserGroupRequest }
     * 
     */
    public AddUserGroupRequest createAddUserGroupRequest() {
        return new AddUserGroupRequest();
    }

    /**
     * Create an instance of {@link AddUserGroupResponse }
     * 
     */
    public AddUserGroupResponse createAddUserGroupResponse() {
        return new AddUserGroupResponse();
    }

    /**
     * Create an instance of {@link UpdateUserGroupRequest }
     * 
     */
    public UpdateUserGroupRequest createUpdateUserGroupRequest() {
        return new UpdateUserGroupRequest();
    }

    /**
     * Create an instance of {@link UpdateUserGroupResponse }
     * 
     */
    public UpdateUserGroupResponse createUpdateUserGroupResponse() {
        return new UpdateUserGroupResponse();
    }

    /**
     * Create an instance of {@link DeleteUserGroupRequest }
     * 
     */
    public DeleteUserGroupRequest createDeleteUserGroupRequest() {
        return new DeleteUserGroupRequest();
    }

    /**
     * Create an instance of {@link DeleteUserGroupResponse }
     * 
     */
    public DeleteUserGroupResponse createDeleteUserGroupResponse() {
        return new DeleteUserGroupResponse();
    }

    /**
     * Create an instance of {@link GetUserGroupByIdRequest }
     * 
     */
    public GetUserGroupByIdRequest createGetUserGroupByIdRequest() {
        return new GetUserGroupByIdRequest();
    }

    /**
     * Create an instance of {@link GetUserGroupByIdResponse }
     * 
     */
    public GetUserGroupByIdResponse createGetUserGroupByIdResponse() {
        return new GetUserGroupByIdResponse();
    }

    /**
     * Create an instance of {@link GetUserGroupIdByNameRequest }
     * 
     */
    public GetUserGroupIdByNameRequest createGetUserGroupIdByNameRequest() {
        return new GetUserGroupIdByNameRequest();
    }

    /**
     * Create an instance of {@link GetUserGroupIdByNameResponse }
     * 
     */
    public GetUserGroupIdByNameResponse createGetUserGroupIdByNameResponse() {
        return new GetUserGroupIdByNameResponse();
    }

}
