//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.17 at 07:44:26 PM PKT 
//


package com.softech.ls360.lcms.api.webservice.client.stub.wsdl.playerutility;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="courseApprovalID" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="courseID" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "courseApprovalID",
    "courseID"
})
@XmlRootElement(name = "InvalidateCourseApprovalCache")
public class InvalidateCourseApprovalCache
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected int courseApprovalID;
    protected int courseID;

    /**
     * Gets the value of the courseApprovalID property.
     * 
     */
    public int getCourseApprovalID() {
        return courseApprovalID;
    }

    /**
     * Sets the value of the courseApprovalID property.
     * 
     */
    public void setCourseApprovalID(int value) {
        this.courseApprovalID = value;
    }

    /**
     * Gets the value of the courseID property.
     * 
     */
    public int getCourseID() {
        return courseID;
    }

    /**
     * Sets the value of the courseID property.
     * 
     */
    public void setCourseID(int value) {
        this.courseID = value;
    }

}
