//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.17 at 07:44:26 PM PKT 
//


package com.softech.ls360.lcms.api.webservice.client.stub.wsdl.playerutility;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LockedCourseStatus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LockedCourseStatus"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="EnrollmentID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LockedStatus" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="FinalMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LockedCourseStatus", propOrder = {
    "enrollmentID",
    "lockedStatus",
    "finalMessage"
})
public class LockedCourseStatus
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "EnrollmentID")
    protected String enrollmentID;
    @XmlElement(name = "LockedStatus")
    protected boolean lockedStatus;
    @XmlElement(name = "FinalMessage")
    protected String finalMessage;

    /**
     * Gets the value of the enrollmentID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnrollmentID() {
        return enrollmentID;
    }

    /**
     * Sets the value of the enrollmentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnrollmentID(String value) {
        this.enrollmentID = value;
    }

    /**
     * Gets the value of the lockedStatus property.
     * 
     */
    public boolean isLockedStatus() {
        return lockedStatus;
    }

    /**
     * Sets the value of the lockedStatus property.
     * 
     */
    public void setLockedStatus(boolean value) {
        this.lockedStatus = value;
    }

    /**
     * Gets the value of the finalMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinalMessage() {
        return finalMessage;
    }

    /**
     * Sets the value of the finalMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinalMessage(String value) {
        this.finalMessage = value;
    }

}
