//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.17 at 07:44:26 PM PKT 
//


package com.softech.ls360.lcms.api.webservice.client.stub.wsdl.playerutility;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.softech.ls360.lcms.api.webservice.client.stub.wsdl.playerutility package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.softech.ls360.lcms.api.webservice.client.stub.wsdl.playerutility
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link HelloWorld }
     * 
     */
    public HelloWorld createHelloWorld() {
        return new HelloWorld();
    }

    /**
     * Create an instance of {@link HelloWorldResponse }
     * 
     */
    public HelloWorldResponse createHelloWorldResponse() {
        return new HelloWorldResponse();
    }

    /**
     * Create an instance of {@link InvalidateCache }
     * 
     */
    public InvalidateCache createInvalidateCache() {
        return new InvalidateCache();
    }

    /**
     * Create an instance of {@link InvalidateCacheResponse }
     * 
     */
    public InvalidateCacheResponse createInvalidateCacheResponse() {
        return new InvalidateCacheResponse();
    }

    /**
     * Create an instance of {@link InvalidateCacheAndNotifyToAllRemainingServers }
     * 
     */
    public InvalidateCacheAndNotifyToAllRemainingServers createInvalidateCacheAndNotifyToAllRemainingServers() {
        return new InvalidateCacheAndNotifyToAllRemainingServers();
    }

    /**
     * Create an instance of {@link InvalidateCacheAndNotifyToAllRemainingServersResponse }
     * 
     */
    public InvalidateCacheAndNotifyToAllRemainingServersResponse createInvalidateCacheAndNotifyToAllRemainingServersResponse() {
        return new InvalidateCacheAndNotifyToAllRemainingServersResponse();
    }

    /**
     * Create an instance of {@link InvalidateCourseConfigurationCache }
     * 
     */
    public InvalidateCourseConfigurationCache createInvalidateCourseConfigurationCache() {
        return new InvalidateCourseConfigurationCache();
    }

    /**
     * Create an instance of {@link InvalidateCourseConfigurationCacheResponse }
     * 
     */
    public InvalidateCourseConfigurationCacheResponse createInvalidateCourseConfigurationCacheResponse() {
        return new InvalidateCourseConfigurationCacheResponse();
    }

    /**
     * Create an instance of {@link InvalidateCourseApprovalCache }
     * 
     */
    public InvalidateCourseApprovalCache createInvalidateCourseApprovalCache() {
        return new InvalidateCourseApprovalCache();
    }

    /**
     * Create an instance of {@link InvalidateCourseApprovalCacheResponse }
     * 
     */
    public InvalidateCourseApprovalCacheResponse createInvalidateCourseApprovalCacheResponse() {
        return new InvalidateCourseApprovalCacheResponse();
    }

    /**
     * Create an instance of {@link GetSessionTimeOutKeyValue }
     * 
     */
    public GetSessionTimeOutKeyValue createGetSessionTimeOutKeyValue() {
        return new GetSessionTimeOutKeyValue();
    }

    /**
     * Create an instance of {@link GetSessionTimeOutKeyValueResponse }
     * 
     */
    public GetSessionTimeOutKeyValueResponse createGetSessionTimeOutKeyValueResponse() {
        return new GetSessionTimeOutKeyValueResponse();
    }

    /**
     * Create an instance of {@link GetAppSettingKeyValue }
     * 
     */
    public GetAppSettingKeyValue createGetAppSettingKeyValue() {
        return new GetAppSettingKeyValue();
    }

    /**
     * Create an instance of {@link GetAppSettingKeyValueResponse }
     * 
     */
    public GetAppSettingKeyValueResponse createGetAppSettingKeyValueResponse() {
        return new GetAppSettingKeyValueResponse();
    }

    /**
     * Create an instance of {@link InvalidateBrandCache }
     * 
     */
    public InvalidateBrandCache createInvalidateBrandCache() {
        return new InvalidateBrandCache();
    }

    /**
     * Create an instance of {@link InvalidateBrandCacheResponse }
     * 
     */
    public InvalidateBrandCacheResponse createInvalidateBrandCacheResponse() {
        return new InvalidateBrandCacheResponse();
    }

    /**
     * Create an instance of {@link GetCourseLockedStatus }
     * 
     */
    public GetCourseLockedStatus createGetCourseLockedStatus() {
        return new GetCourseLockedStatus();
    }

    /**
     * Create an instance of {@link GetCourseLockedStatusResponse }
     * 
     */
    public GetCourseLockedStatusResponse createGetCourseLockedStatusResponse() {
        return new GetCourseLockedStatusResponse();
    }

    /**
     * Create an instance of {@link ArrayOfLockedCourseStatus }
     * 
     */
    public ArrayOfLockedCourseStatus createArrayOfLockedCourseStatus() {
        return new ArrayOfLockedCourseStatus();
    }

    /**
     * Create an instance of {@link LockedCourseStatus }
     * 
     */
    public LockedCourseStatus createLockedCourseStatus() {
        return new LockedCourseStatus();
    }

}
